http:
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
          - middlewares-realip
          - middlewares-bouncer
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-compress