http:
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
          - middlewares-bouncer
          - middlewares-realip #This middleware can't be first
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-compress