global:
  scrape_interval: 10s

scrape_configs:
- job_name: vmagent
  static_configs:
    - targets:
      - traefik-vmagent.%{SERVER_ADDRESS}:8429
- job_name: vlagent
  static_configs:
    - targets:
      - traefik-vlagent.%{SERVER_ADDRESS}:9429
- job_name: 'traefik'
  static_configs:
    - targets: 
      - traefik.%{SERVER_ADDRESS}:8080